# Generated by Django 2.0.2 on 2018-07-02 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concession',
            name='date_consession_end',
            field=models.DateField(blank=True, default=datetime.date(2018, 7, 2)),
        ),
        migrations.AlterField(
            model_name='concession',
            name='date_consession_start',
            field=models.DateField(default=datetime.date(2018, 7, 2)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='date_pay',
            field=models.DateField(blank=True, default=datetime.date(2018, 7, 2)),
        ),
    ]
